<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
	<title>Techfive ICT Sunglasses</title>
    <link rel="stylesheet" href="style.css" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <title></title>
</head>
<body>
	 <section class="header">
			<div class="container">
				<nav class="navbar navbar-expand-lg navbar-light">
					<a class="navbar-brand" href="Homepage.aspx"><img src="../Images/ICT%20Sunglasses%20Logo%20(2).png" /></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false">
						<i class="fa fa-bars"></i>
					</button>

					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav ml-auto text-right">
						<li class="nav-item">
							<a class="nav-link active-home" href="Homepage.aspx">HOME</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">SOMETHING HERE</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							PRODUCTS
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="WomenPage.aspx">Woman</a>
								<a class="dropdown-item" href="MenPage.aspx">Men</a>
								<a class="dropdown-item" href="ChildrenPage.aspx">Childen</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="SalePage.aspx">SALE</a>
							</div>
						</li> 
						<li class="nav-item">
							<a class="nav-link" href="Login.aspx">LOG IN</a>
						</li>
						</ul> 
					</div>
				</nav>
			</div>
	 </section>
   
    
    </form>

</body>
</html>